### ISSUE TITLE
Multi Module Project - Gradle

### ISSUE THREAD

**Issue by FlorianLautenschlager** [TouK/sputnik#141]
Does Sputnik supports a multi module project, such as https://github.com/ChronixDB/chronix.api ?

**Comment by rafalnowak** [comment]
Yes, Sputnik should work with multi module project. Have you encountered any problems in your particular repository?

**Comment by FlorianLautenschlager** [comment]
For the mentioned project Sputnik does not find any files with the allowed extension.
````
Total 0 of 1 files had allowed extensions [java]
```
I followed the configuration guide:

1) Choosed gradle as build tool (I made no changes to gradle)
2) Added the after_sucess to [.travis.yml](https://github.com/ChronixDB/chronix.api/blob/master/.travis.yml)

Do i miss any configuration setting?

Thx

**Comment by rafalnowak** [comment]
I've looked into Travis logs for your build. 

There isn't any problem with Sputnik configuration. The way Sputnik works looks like that:
1. You make pull request to your code, with changes in actual Java files - or in other language that is supported by us.
2. Pull request is being built by Travis and integration script runs Sputnik.
3. Now the essence - Sputnik checks on changes that you made in this pull request. That means, that it will run code review only on files that participate in your pull request change.

In your case you have made change in *.gradle file, so Sputnik did not find any changes in Java files to review.

Last note, please remember that if your problem is about Sputnik.ci, report issues in repository: https://github.com/TouK/sputnik-ci

I hope that helps with using Sputnik :)

**Comment by FlorianLautenschlager** [comment]
Ok - my fault... Thx for your help. 
By the way: I really missed a platform for github such as sputnik-ci. Nice job!
